# Generated by Django 4.2 on 2023-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                default=False, to="main.tag", verbose_name="Направление"
            ),
        ),
    ]
